### ISSUE TITLE
upgrade to train

### ISSUE THREAD

**Issue by chuan137** [sapcc/ironic#10]
* commit list diff
* pull request created

**Comment by chuan137** [comment]
* 2018-08-14 0965915 - Do not filter out ports belonging to a port-group [Fabian Wiesel] (1 year, 4 months ago)
AB: does it make sense anymore?

**Comment by chuan137** [comment]
>     * * 2018-08-22 [244b1a5](https://github.com/sapcc/ironic/commit/244b1a549ce25d6151c71f99b9a5e4efa6c1ae94) - Delete all ports, not only pxe_enabled ones [Fabian Wiesel] (1 year, 4 months ago)
**can remove** similar logic in [upstream](https://github.com/openstack/ironic/blob/855986c0244d31f02cc6712b4669b2069ae3bcc1/ironic/common/neutron.py#L416)

**Comment by chuan137** [comment]
- [ ] 54a25a1c4 (HEAD -> stable/rocky-m3, origin/stable/rocky-m3, origin/HEAD) Adds python-openstackclient to custom-requirements
- [ ] 5dc784076 adds driver dependencies to custom req
- [ ] 306f4a008 Update custom-requirements.txt
- [ ] 77be84fc5 switches ironic-inspector dependency to sapcc fork
- [ ] 50a115576 adds mdns for ironic-inspector
- [ ] 96673eaaf Update custom-requirements.txt
- [ ] 7dc10e25c Update custom-requirements.txt
- [ ] fd04c9818 adds ironic-inspecto to custom-requirements
- [ ] ab8212a44 adds python-ironic-inspector-client to custom-requirements
- [ ] c8e0e6e54 Adds ipmitool to custom-requirements
- [ ] c9b4c78aa Adds pxe tftpmap.py to enable it on loci image
- [ ] 2bd0d7f34 Adds the tftpmap.py file for the pxe loci image
- [ ] 08215ce78 Changes ptftpd custom-requirements to forked repo
- [ ] b414492b2 adds ptftpd to custom-requirements
- [ ] 45564b56a Adds redis to custom-requirements
- [ ] f4bc2d0d7 Adds raven to custom-requirements for loci image
- [ ] 78bca6205 Merge pull request #8 from sapcc/BerndKue-patch-1
- [ ] 0e3d301b2 Missing $ in variable
- [ ] 5323b3d03 Merge pull request #7 from sapcc/stefanhipfel-patch-1
- [ ] 07e174485 Update manager.py
- [ ] 2e023901a Fixes AttributeError in the remove ports after failed cleanup
- [ ] 6dff42e11 Merge pull request #6 from sapcc/stefanhipfel-patch-1
- [ ] 747971566 Reverts test_provision_node_in_maintenance_fail changes
- [ ] f6ace240b Fix wrong argument name for @lru_cache
- [ ] c48116f71 Fix Swift session paramters and auth client caching
- [ ] 8181b4de1 Fix version discovery
- [ ] 8d9e3479e Revert "allow to provision nodes in maintenance"
- [ ] c50da4dee Revert "use default ucs sdk version."
- [ ] ab05983c9 use default ucs sdk version.
- [ ] 436b15fe5 Add option for disabling proxydhcp
- [ ] 5b28daa6b Do not fail on missing labels in glance image properties
- [ ] dc325728e Remove ports from cleaning network prior provisioning
- [ ] 2aece7e61 Fix for instance_info capabilities which is a unicode, but treated as dict
- [ ] 3406bc2b2 Ensure tenant network is unconfigured
- [ ] 9960d5212 Various test fixes
- [ ] 515b92b12 UcsSdk from own branch
- [ ] a066d96d9 Squash of changes from pike
- [ ] 0670bd75d UcsSdk from own branch
- [ ] 43d5ef115 Configurable swift-account for the logs
